### ISSUE TITLE
Unable to dispense medicine that exists

### ISSUE THREAD

**Issue by suenalaba** [suenalaba/pe#7]
I had to adjust date time to test the expiry date feature.
However, a better error prompt could be given: For example, the medicine cannot be dispensed as it's already expired etc, instead of saving there is not enough medicine to dispense as the medicine clearly exists in the view medicine list.

![ab304c6f002bfdacde4e16f0c6aa11ba.png](https://raw.githubusercontent.com/suenalaba/pe/main/files/8b42f043-79d0-48d8-a6e0-2774fe211796.png)

**Comment by nus-pe-script** [comment]
Your response not required for this bug as the team has accepted the bug as it is.
